WINDOW_WIDTH = 800
WINDOW_HEIGHT = 800
MAX_Y = +WINDOW_HEIGHT / 2
MIN_Y = -MAX_Y
MAX_X = WINDOW_WIDTH / 2
MIN_X = -MAX_X
RENDER_DELAY = 1 / 30  # means 30 fps?

NO_OF_ENEMIES_PER_ROW = 4
NO_OF_ENEMY_ROWS = 3
